// import apiClient from '../lib/axios';


const mockNews = [
    { id: 1, category: 'Môi trường', date: '15/06/2025', title: 'Chiến dịch "Chủ nhật Xanh": Khi hành động nhỏ tạo nên thay đổi lớn', description: 'Đều đặn mỗi tuần, màu áo xanh của sinh viên OU lại phủ khắp các công viên, tuyến đường để thu gom rác thải, lan tỏa thông điệp sạch.', content: 'Không cần những hành động vĩ mô, chiến dịch "Chủ nhật Xanh" của CLB OU Green Plus là minh chứng cho việc tình yêu môi trường bắt nguồn từ những điều bình dị nhất. Mỗi sáng Chủ nhật, các bạn sinh viên lại cùng nhau tập trung, mang theo dụng cụ và tỏa ra các khu vực công cộng để dọn dẹp vệ sinh. Hoạt động không chỉ làm sạch cảnh quan mà còn nâng cao ý thức của người dân địa phương, tạo nên một hiệu ứng cộng đồng tích cực.', image: 'https://images.unsplash.com/photo-1618479125207-a273014c462a?q=80&w=2940&auto=format&fit=crop'},
    { id: 2, category: 'Cộng đồng', date: '12/05/2025', title: 'Nhìn lại hành trình Mùa Hè Xanh 2024 đầy cảm xúc', description: 'Một tháng tình nguyện tại các vùng quê khó khăn đã để lại vô vàn kỷ niệm và những công trình ý nghĩa cho bà con.', content: 'Chiến dịch Mùa Hè Xanh 2024 của sinh viên trường ĐH Mở TP.HCM đã khép lại với nhiều thành công rực rỡ. Các chiến sĩ tình nguyện đã hoàn thành xuất sắc các nhiệm vụ như xây dựng nhà tình bạn, làm đường bê tông nông thôn, tổ chức các lớp học hè cho trẻ em và các hoạt động tuyên truyền về sức khỏe, môi trường. Đây không chỉ là một chuyến đi cống hiến mà còn là một hành trình trưởng thành, giúp các bạn sinh viên thấu hiểu hơn về cuộc sống và giá trị của sự cho đi.', image: 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?q=80&w=2940&auto=format&fit=crop'},
    { id: 3, category: 'Môi trường', date: '28/04/2025', title: 'Green+ Tour: Hành trình lan tỏa lối sống xanh trong giảng đường', description: 'Chuỗi trạm thông tin và trò chơi tương tác của OU Green Plus đã thu hút hàng ngàn sinh viên tham gia và cam kết hành động.', content: 'Với mô hình độc đáo, Green+ Tour đã "phủ xanh" các cơ sở của trường ĐH Mở. Tại mỗi trạm, sinh viên được tham gia các trò chơi về phân loại rác, tìm hiểu về các sản phẩm tái chế và nhận những phần quà xanh. Dự án đã thành công trong việc biến những kiến thức môi trường khô khan trở nên gần gũi và thú vị hơn bao giờ hết.', image: 'https://images.unsplash.com/photo-1542744095-291d1f67b221?q=80&w=2940&auto=format&fit=crop'},
    { id: 4, category: 'Môi trường', date: '22/04/2025', title: 'Ngày Trái Đất: Đổi rác điện tử lấy cây xanh', description: 'Hưởng ứng Ngày Trái Đất, OU Green Plus tổ chức ngày hội thu gom pin, thiết bị điện tử cũ và đổi lấy cây sen đá, lan tỏa thông điệp tái chế.', content: 'Rác thải điện tử là một vấn đề nhức nhối. Nhận thức được điều đó, ngày hội "Đổi rác điện tử lấy cây xanh" đã được tổ chức và nhận được sự hưởng ứng nhiệt tình. Hàng trăm viên pin, điện thoại cũ, dây sạc... đã được thu gom đúng cách, đổi lại là những chậu cây xanh mướt được trao tận tay các bạn sinh viên, như một lời nhắc nhở về một vòng tuần hoàn mới.', image: 'https://images.unsplash.com/photo-1604147706283-d7119b5b822c?q=80&w=2874&auto=format&fit=crop'},
    { id: 5, category: 'Cộng đồng', date: '10/03/2025', title: 'Tọa đàm "Net Zero và vai trò của người trẻ"', description: 'Buổi tọa đàm với các chuyên gia hàng đầu đã cung cấp cho sinh viên góc nhìn sâu sắc về mục tiêu Net Zero và những gì thế hệ trẻ có thể làm.', content: 'Net Zero không còn là một khái niệm xa vời. Buổi tọa đàm đã giúp các bạn sinh viên hiểu rõ hơn về tầm quan trọng của việc giảm phát thải, vai trò của năng lượng tái tạo và những hành động thiết thực mà mỗi cá nhân có thể đóng góp. Sự kiện đã thắp lên ngọn lửa nhiệt huyết, thôi thúc người trẻ hành động vì một tương lai bền vững.', image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=3132&auto=format&fit=crop'},
    { id: 6, category: 'Cộng đồng', date: '20/01/2025', title: 'Chương trình "Xuân Tình Nguyện" mang Tết về vùng cao', description: 'Những món quà, những lời chúc và những hoạt động ý nghĩa đã được các tình nguyện viên mang đến cho bà con và trẻ em vùng sâu vùng xa.', content: 'Với mong muốn không để ai bị bỏ lại phía sau, chương trình "Xuân Tình Nguyện" đã được tổ chức thành công tốt đẹp. Các tình nguyện viên đã trao tặng hàng trăm phần quà Tết, tổ chức các trò chơi dân gian và gói bánh chưng cùng bà con. Chuyến đi đã để lại những dấu ấn khó phai về tình người và sự sẻ chia ấm áp.', image: 'https://images.unsplash.com/photo-1601878783425-937b5634b344?q=80&w=2952&auto=format&fit=crop'},
    { id: 7, category: 'Môi trường', date: '15/11/2024', title: 'Workshop "Tái chế thông minh": Sáng tạo từ vật liệu cũ', description: 'Sinh viên hào hứng tham gia buổi workshop biến chai nhựa, giấy báo cũ thành những vật dụng trang trí độc đáo và hữu ích.', content: 'Dưới sự hướng dẫn của các chuyên gia, những vật liệu tưởng chừng bỏ đi đã được "hồi sinh" thành các sản phẩm đẹp mắt như lọ hoa, hộp bút, đồ trang trí... Workshop không chỉ dạy về kỹ năng thủ công mà còn truyền tải một thông điệp mạnh mẽ về việc hạn chế tiêu dùng và tận dụng tối đa những gì chúng ta đang có.', image: 'https://images.unsplash.com/photo-1604187351543-0375681ba453?q=80&w=2874&auto=format&fit=crop'},
    { id: 8, category: 'Cộng đồng', date: '01/10/2024', title: 'Chương trình "Trung thu cho em" tại mái ấm tình thương', description: 'Những chiếc lồng đèn, những phần bánh kẹo và những nụ cười rạng rỡ đã được trao đến các em nhỏ có hoàn cảnh đặc biệt.', content: 'Một mùa Trung thu nữa lại về, và CLB OU Green Plus đã mang một không khí lễ hội ấm áp đến với các em nhỏ tại mái ấm tình thương. Đêm hội đã diễn ra với nhiều hoạt động sôi nổi như rước đèn, phá cỗ, văn nghệ... Mỗi nụ cười của các em là động lực to lớn để CLB tiếp tục hành trình phụng sự cộng đồng của mình.', image: 'https://images.unsplash.com/photo-1540221336024-d7f34772e8a1?q=80&w=2940&auto=format&fit=crop'},
    { id: 9, category: 'Môi trường', date: '05/06/2024', title: 'Hưởng ứng Ngày Môi trường Thế giới tại Cần Giờ', description: 'Hàng trăm sinh viên đã cùng nhau thu gom rác thải, làm sạch nhiều km bờ biển và trồng cây ngập mặn.', content: 'Để hưởng ứng Ngày Môi trường Thế giới, một hoạt động quy mô lớn đã được tổ chức tại khu dự trữ sinh quyển Cần Giờ. Các bạn sinh viên không ngại khó khăn, làm việc hăng say dưới nắng để trả lại vẻ đẹp vốn có cho bờ biển. Hoạt động này cũng góp phần nâng cao ý thức về việc bảo vệ hệ sinh thái rừng ngập mặn quan trọng này.', image: 'https://images.unsplash.com/photo-1617953141905-cde72605cff5?q=80&w=2940&auto=format&fit=crop'},
    { id: 10, category: 'Môi trường', date: '25/05/2024', title: 'Phát động cuộc thi "Sáng kiến Xanh" trong sinh viên', description: 'Cuộc thi tìm kiếm và ươm mầm các dự án, ý tưởng đột phá của sinh viên nhằm giải quyết các vấn đề môi trường tại địa phương.', content: 'Với mong muốn phát huy trí tuệ và sự sáng tạo của người trẻ, cuộc thi "Sáng kiến Xanh" đã được phát động. Đây là sân chơi để các bạn sinh viên thể hiện ý tưởng của mình, từ các ứng dụng công nghệ, các mô hình kinh doanh bền vững cho đến các giải pháp truyền thông sáng tạo. Những ý tưởng xuất sắc nhất sẽ nhận được sự hỗ trợ để hiện thực hóa.', image: 'https://images.unsplash.com/photo-1579543944358-a9263901e18e?q=80&w=2874&auto=format&fit=crop'}
];



export const getAllNews = async () => {
  console.log('Đang lấy tất cả tin tức...');
  await new Promise(resolve => setTimeout(resolve, 500));
  return mockNews;
};

const fakeApiCall = (data) => new Promise(resolve => setTimeout(() => resolve(data), 500));

export const getProjects = () => fakeApiCall(mockProjects);
export const getProjectById = (id) => fakeApiCall(mockProjects.find(p => p.id === parseInt(id)));
export const getNews = () => fakeApiCall(mockNews);
export const getNewsById = (id) => fakeApiCall(mockNews.find(n => n.id === parseInt(id)));